sudo: required

language: java

jdk:
  - openjdk11

matrix:
  include:
    - jdk: openjdk11
      before_install:
        - sudo rm "${JAVA_HOME}/lib/security/cacerts"
        - sudo ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew clean build buildDockerImage -Djavax.net.ssl.trustStorePassword=changeit

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew pushDockerImages -Djavax.net.ssl.trustStorePassword=changeit
    on:
      branch: master
