sudo: required

language: java

jdk:
  - oraclejdk11

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew clean build buildDockerImage 

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew pushDockerImages 
    on:
      branch: master
