sudo: required

language: java

jdk:
  - oraclejdk13

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - export PATH=$JAVA_HOME/bin:$PATH
  - ./gradlew clean build buildDockerImage -Djavax.net.ssl.trustStorePassword=changeit

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew pushDockerImages -Djavax.net.ssl.trustStorePassword=changeit
    on:
      branch: master
